export const CREATE_USER = "CREATE_USER"
export const RETRIEVE_USERS = "RETRIEVE_USERS"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"

export const RETRIEVE_DASHBOARD_DATA = "RETRIEVE_DASHBOARD_DATA"
export const RETRIEVE_SUPPLIER_DASHBOARD_DATA = "RETRIEVE_SUPPLIER_DASHBOARD_DATA"

export const RETRIEVE_SITES = "RETRIEVE_SITES"
export const RETRIEVE_ADDRESSES = "RETRIEVE_ADDRESSES"
export const RETRIEVE_CARRIERS = "RETRIEVE_CARRIERS"
export const RETRIEVE_DELIVERY_MODES = "RETRIEVE_DELIVERY_MODES"

export const RETRIEVE_SITES_BY_ID = "RETRIEVE_SITES_BY_ID"

export const RETRIEVE_ROLES = "RETRIEVE_ROLES"

export const RETRIEVE_CUSTOMERS = "RETRIEVE_CUSTOMERS"

export const RETRIEVE_BUSINESS_PARTNERS = "RETRIEVE_BUSINESS_PARTNERS"
export const RETRIEVE_LANGUAGES = "RETRIEVE_LANGUAGES"
export const RETRIEVE_DESIGNATIONS = "RETRIEVE_DESIGNATIONS"

export const RETRIEVE_CONTACT = "RETRIEVE_CONTACT"
export const CREATE_CONTACT = "CREATE_CONTACT"
export const UPDATE_CONTACT = "UPDATE_CONTACT"
export const DELETE_CONTACT = "DELETE_CONTACT"

export const RETRIEVE_CUSTOMER_CONCODE = "RETRIEVE_CUSTOMER_CONCODE"

export const RETRIEVE_SUPPLIERS = "RETRIEVE_SUPPLIERS"

export const RETRIEVE_SUPPLIER_CONCODE = "RETRIEVE_SUPPLIER_CONCODE"

export const RETRIEVE_RETURNS = "RETRIEVE_RETURNS"
export const RETRIEVE_ORDERS = "RETRIEVE_ORDERS"
export const RETRIEVE_QUOTES = "RETRIEVE_QUOTES"
export const RETRIEVE_PAYMENTS = "RETRIEVE_PAYMENTS"
export const RETRIEVE_INVOICES_OPEN_PAYMENTS = "RETRIEVE_INVOICES_OPEN_PAYMENTS"
export const RETRIEVE_PURCHASE_ORDERS = "RETRIEVE_PURCHASE_ORDERS"

export const RETRIEVE_PICKUP_REQUESTS = "RETRIEVE_PICKUP_REQUESTS"
export const CREATE_PICKUP_REQUEST = "CREATE_PICKUP_REQUEST"
export const DELETE_PICKUP_REQUEST = "DELETE_PICKUP_REQUEST"

export const RETRIEVE_DROP_REQUESTS = "RETRIEVE_DROP_REQUESTS"
export const CREATE_DROP_REQUEST = "CREATE_DROP_REQUEST"
export const CREATE_DROP_B2C_REQUEST = "CREATE_DROP_B2C_REQUEST"
export const DELETE_DROP_REQUEST = "DELETE_DROP_REQUEST"
export const RETRIEVE_PRODUCT_CONSUMPTIONS = "RETRIEVE_PRODUCT_CONSUMPTIONS"


export const RETRIEVE_SERVICE_REQUESTS = "RETRIEVE_SERVICE_REQUESTS"
export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST"
export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST"

export const RETRIEVE_SOCART_REQUESTS = "RETRIEVE_SOCART_REQUESTS"
export const CREATE_SOCART_REQUEST = "CREATE_SOCART_REQUEST"
export const DELETE_SOCART_REQUEST = "DELETE_SOCART_REQUEST"

export const RETRIEVE_DELIVERIES = "RETRIEVE_DELIVERIES"

export const RETRIEVE_INVOICES = "RETRIEVE_INVOICES"

export const RETRIEVE_CREDITNOTES = "RETRIEVE_CREDITNOTES"

export const RETRIEVE_RECEIPTS = "RETRIEVE_RECEIPTS"

export const RETRIEVE_PURCHASE_INVOICES = "RETRIEVE_PURCHASE_INVOICES"

export const RETRIEVE_MAP_DATA = "RETRIEVE_MAP_DATA"

export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS"
export const RETRIEVE_PRODUCTS_PRICE = "RETRIEVE_PRODUCTS_PRICE"
export const RETRIEVE_PRODUCTCATEG = "RETRIEVE_PRODUCTCATEG"
export const RETRIEVE_INSTALL_BASE = "RETRIEVE_INSTALL_BASE"

export const RETRIEVE_ANNOUNCEMENTS = "RETRIEVE_ANNOUNCEMENTS"
export const CREATE_ANNOUNCEMENT = "CREATE_ANNOUNCEMENT"
export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT"
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT"

export const RETRIEVE_DOCUMENTS = "RETRIEVE_DOCUMENTS"
export const CREATE_DOCUMENT = "CREATE_DOCUMENT"
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT"
export const DELETE_DOCUMENT = "DELETE_DOCUMENT"

export const RETRIEVE_DISCUSSION_FORUMS = "RETRIEVE_DISCUSSION_FORUMS"
export const CREATE_DISCUSSION_FORUM = "CREATE_DISCUSSION_FORUM"
export const UPDATE_DISCUSSION_FORUM = "UPDATE_DISCUSSION_FORUM"
export const DELETE_DISCUSSION_FORUM = "DELETE_DOCUMENT"